apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: test-workflow demo test
permissions:
  scm-token-own: read
on:
  pull_request:
    branches:
      - "master"
  push:
  	branches:
  	  - "master"    
  workflow_dispatch:
jobs:
  build:
    steps:
      - name: Checkout repository
        uses: cloudbees-io/checkout@v1
        with:
          path: simple-maven-project-with-tests
      - name: Setup git credentials
        uses: cloudbees-io/configure-git-global-credentials@v1
      - name: Run tests
        kind: test
        uses: docker://maven:3-eclipse-temurin-21-alpine
        run: |
          set -x
          cd simple-maven-project-with-tests
          mvn -B -ntp test
      - name: Publish test results
        kind: test
        if: ${{always()}}
        uses: cloudbees-io/publish-test-results@v2
        with:
          test-type: junit
          results-path: ./target/surefire-reports/
